=== Eldam/testJenkins/test/resources/datasets/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (user*, event*, user_event*)>

<!ELEMENT user EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT user_event EMPTY>
<!ATTLIST user
	id  CDATA #IMPLIED
    login CDATA #IMPLIED
    password CDATA #IMPLIED
    name CDATA #IMPLIED
    surname CDATA #IMPLIED
    email CDATA #IMPLIED
    inscription_date CDATA #IMPLIED
>
<!ATTLIST event
	id  CDATA #IMPLIED
    name CDATA #IMPLIED
    description CDATA #IMPLIED
    date CDATA #IMPLIED
    time CDATA #IMPLIED
    category CDATA #IMPLIED
    maxInscriptions CDATA #IMPLIED
    location CDATA #IMPLIED
>
<!ATTLIST user_event
	id  CDATA #IMPLIED
    id_user CDATA #IMPLIED
    id_event CDATA #IMPLIED
    moderator CDATA #IMPLIED
>

=== Eldam/testJenkins/test/resources/datasets/dataset-event-delete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">

<dataset>
	<user id= "1" login="admin" password="2bdc94a3ae40227246a17831b833ba9047b4ff2778180b1a1c0c303e248e574e" name="Antonio" surname="González" email="Antonio@email.com" inscription_date="2018-01-01" />
	<user id= "2" login="marco" password="905d5c1331987f8670ff86955788628bda62ea165cc4c2c5b44b6402b669274d" name="Marco Aurelio" surname="González" email="marco@email.com" inscription_date="2018-01-02" />
	<user id= "3" login="uxio" password="fc3c150e4032998daff4a4cf51b0a047e43616c42df447dff1a36c1c52fcea97" name="Uxío" surname="González Fernández" email="uxio@email.com" inscription_date="2018-01-03" />
	<user id= "4" login="alex" password="e6707bbebab392fbac2ed0f63388ee2388839f9133a27461f221231a27a540bb" name="Alex" surname="Pérez" email="alex@email.com" inscription_date="2018-01-04" />
	<user id= "5" login="victor" password="a67d077fb31b1b890c0f2f98651e402488faa41b095a4d935c2aff337d01f079" name="Victor" surname="Rodríguez" email="victor@email.com" inscription_date="2018-01-05" />
	<user id= "6" login="brais" password="5a9a2a1c917e8b8d94802dd31a0334802c4c86a19b48dfa4e51a546ef81375c7" name="Brais" surname="Coto" email="victor@email.com" inscription_date="2018-01-06" />
	<user id= "7" login="manu" password="defa1c40090e0e7b8d20c28b4b9d921e6f5e1b932d8ffb1b3c9f82896f16c0ca" name="Manuel" surname="Gil" email="manu@email.com" inscription_date="2018-01-07" />
	<user id= "8" login="guillermo" password="1138106e49b5545514428dc22d1c94de70e97f885d7ee24cbe168d86267a2e4f" name="Guillermo" surname="Pazos" email="guillermo@email.com" inscription_date="2018-01-08" />
	<user id= "9" login="Gabriel" password="24e7655da3cee593d83f8dd2dcd1d9947e14860e3b48142a026dfda6d2d2f83b" name="Gabriel" surname="Estevez" email="gabriel@email.com" inscription_date="2018-01-09" />
	<user id= "10" login="Miguel" password="6b35bc5c2d00d9b95cf2c4a01aad68d70ae6e6da19257e9bd82a34e29cc8afbb" name="Miguel" surname="Paz" email="miguel@email.com" inscription_date="2018-01-10" />

	<event id= "1" name="Cineforum American Beauty" description="Discusión sobre la película" date="2018-01-01" time="01:00:00" category="Cine" maxInscriptions="23" location="Ponte Vella, Ourense"/>
	<event id= "2" name="Cineforum American history X" description="Discusión sobre la película" date="2018-02-02" time="02:00:00" category="Cine" maxInsciptions="45" location="Ponte Vella, Ourense"/>
	<event id= "3" name="Lectura de libro Las Dos Torres" description="Lectura de trozos del libro por distintas personalidades" date="2018-03-03" time="03:00:00" category="Literatura" maxInscriptions="60" location="Biblioteca Municipal, Ourense"/>
	<event id= "4" name="Visionado de partido LFP" description="Reunión para ver el partido Levante-Leganés" date="2018-04-04" time="04:00:00" category="Deportes" maxInscriptions="50" location="Bar Eurosport, Ourense"/>
	
	<user_event id= "1" id_user="1" id_event="1" moderator="1"/>
	<user_event id= "2" id_user="2" id_event="1" moderator="0"/>
	<user_event id= "3" id_user="3" id_event="1" moderator="0"/>
	<user_event id= "4" id_user="4" id_event="1" moderator="0"/>
	<user_event id= "5" id_user="5" id_event="1" moderator="0"/>
	<user_event id= "6" id_user="6" id_event="1" moderator="0"/>
	<user_event id= "7" id_user="7" id_event="1" moderator="0"/>
	<user_event id= "8" id_user="8" id_event="2" moderator="1"/>
	<user_event id= "9" id_user="7" id_event="2" moderator="0"/>
	<user_event id= "10" id_user="6" id_event="2" moderator="0"/>
	<user_event id= "11" id_user="1" id_event="3" moderator="1"/>
	<user_event id= "12" id_user="2" id_event="4" moderator="1"/>
	<user_event id= "13" id_user="3" id_event="4" moderator="0"/>
	<user_event id= "14" id_user="4" id_event="5" moderator="1"/>
	<user_event id= "15" id_user="5" id_event="5" moderator="0"/>
	<user_event id= "16" id_user="6" id_event="5" moderator="0"/>
	<user_event id= "17" id_user="7" id_event="6" moderator="1"/>
	<user_event id= "18" id_user="8" id_event="6" moderator="0"/>
	<user_event id= "20" id_user="10" id_event="8" moderator="1"/>
	<user_event id= "21" id_user="1" id_event="8" moderator="1"/>
	<user_event id= "22" id_user="2" id_event="9" moderator="1"/>
	<user_event id= "23" id_user="2" id_event="9" moderator="0"/>
	<user_event id= "24" id_user="3" id_event="10" moderator="1"/>
</dataset>
